---
- name: Verify Kubernetes Nodes Status
  hosts: master-node-1
  become: true
  gather_facts: true
  tasks:
    - name: Get Kubernetes Nodes Status
      ansible.builtin.shell: |
        export KUBECONFIG=/opt/kubernetes/.kube/config
        kubectl get nodes --no-headers
      register: kube_nodes
      changed_when: false

    - name: Debug Node Status Output
      ansible.builtin.debug:
        msg: "{{ kube_nodes.stdout_lines }}"

    - name: Fail if any node is not Ready
      ansible.builtin.fail:
        msg: "One or more Kubernetes nodes are NOT in Ready state!"
      when: "' Ready ' not in item"
      loop: "{{ kube_nodes.stdout_lines }}"
