---
platforms: 
  - name: instance-2
driver:
  name: default

provisioner:
  name: ansible
  env_file: .env
  inventory:
    links:
      hosts: inventory/hosts.yaml
      group_vars: inventory/group_vars
  playbooks:
    side_effect: side_effect/default.yaml

    

scenario:
  name: test-cluster
  test_sequence:
    - create
    - converge
    - side_effect side_effect/rotate_certs.yaml
    - verify tests/test_rotate_certs.yaml
    - side_effect side_effect/patch_os_security.yaml
    - verify tests/test_patch_os_security.yaml
    - destroy

verifier:
  name: ansible