---
kubernetes_version: "v1.32.0"
loadbalancer_apiserver: "{{ hostvars[groups['loadbalancer'][0]]['ansible_host'] }}"
haproxy_listen_port: 6443

etcd_version: "3.5.16-0"
etcd_data_dir: "/var/lib/etcd"
etcd_peer_port: 2380
etcd_client_port: 2379

kubernetes_cluster_architecture: "stacked-etcd" # "external-etcd" or "stacked-etcd"

coredns_version: "v1.11.3"


